// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: point.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码定义 (区间: 60000-69999)
type PointErrorCode int32

const (
	PointErrorCode_POINT_SUCCESS PointErrorCode = 0
	// POINT_INTERNAL_ERROR 复用 gocommon 通用内部错误码 10005，与通用码区间对齐。
	PointErrorCode_POINT_INTERNAL_ERROR     PointErrorCode = 10005
	PointErrorCode_POINT_NOT_FOUND          PointErrorCode = 60001 // 账户 / 规则不存在
	PointErrorCode_POINT_BAD_REQUEST        PointErrorCode = 60002 // 参数非法
	PointErrorCode_POINT_INSUFFICIENT       PointErrorCode = 60003 // 积分不足
	PointErrorCode_POINT_ALREADY_CHECKED_IN PointErrorCode = 60004 // 当日已签到
	PointErrorCode_POINT_RULE_NOT_FOUND     PointErrorCode = 60005 // 规则不存在
	PointErrorCode_POINT_LIMIT_REACHED      PointErrorCode = 60006 // 已达到规则限次
)

// Enum value maps for PointErrorCode.
var (
	PointErrorCode_name = map[int32]string{
		0:     "POINT_SUCCESS",
		10005: "POINT_INTERNAL_ERROR",
		60001: "POINT_NOT_FOUND",
		60002: "POINT_BAD_REQUEST",
		60003: "POINT_INSUFFICIENT",
		60004: "POINT_ALREADY_CHECKED_IN",
		60005: "POINT_RULE_NOT_FOUND",
		60006: "POINT_LIMIT_REACHED",
	}
	PointErrorCode_value = map[string]int32{
		"POINT_SUCCESS":            0,
		"POINT_INTERNAL_ERROR":     10005,
		"POINT_NOT_FOUND":          60001,
		"POINT_BAD_REQUEST":        60002,
		"POINT_INSUFFICIENT":       60003,
		"POINT_ALREADY_CHECKED_IN": 60004,
		"POINT_RULE_NOT_FOUND":     60005,
		"POINT_LIMIT_REACHED":      60006,
	}
)

func (x PointErrorCode) Enum() *PointErrorCode {
	p := new(PointErrorCode)
	*p = x
	return p
}

func (x PointErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PointErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_point_proto_enumTypes[0].Descriptor()
}

func (PointErrorCode) Type() protoreflect.EnumType {
	return &file_point_proto_enumTypes[0]
}

func (x PointErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PointErrorCode.Descriptor instead.
func (PointErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{0}
}

// 积分账户
type UserPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`                            // 当前可用积分
	TotalEarned   int64                  `protobuf:"varint,3,opt,name=total_earned,json=totalEarned,proto3" json:"total_earned,omitempty"` // 累计获得
	TotalSpent    int64                  `protobuf:"varint,4,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`    // 累计消费
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPoint) Reset() {
	*x = UserPoint{}
	mi := &file_point_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPoint) ProtoMessage() {}

func (x *UserPoint) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPoint.ProtoReflect.Descriptor instead.
func (*UserPoint) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{0}
}

func (x *UserPoint) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserPoint) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UserPoint) GetTotalEarned() int64 {
	if x != nil {
		return x.TotalEarned
	}
	return 0
}

func (x *UserPoint) GetTotalSpent() int64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

func (x *UserPoint) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 积分流水（对账 / 审计）
type PointLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                                 // 正=获得，负=消费
	BalanceAfter  int64                  `protobuf:"varint,4,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"` // 变动后余额
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                                      // earn / spend / admin_adjust
	RuleCode      string                 `protobuf:"bytes,6,opt,name=rule_code,json=ruleCode,proto3" json:"rule_code,omitempty"`              // 命中的规则 code（空表示非规则触发）
	RelatedType   string                 `protobuf:"bytes,7,opt,name=related_type,json=relatedType,proto3" json:"related_type,omitempty"`     // article / background ...
	RelatedId     uint32                 `protobuf:"varint,8,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"`
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointLog) Reset() {
	*x = PointLog{}
	mi := &file_point_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointLog) ProtoMessage() {}

func (x *PointLog) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointLog.ProtoReflect.Descriptor instead.
func (*PointLog) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{1}
}

func (x *PointLog) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PointLog) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PointLog) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PointLog) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *PointLog) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PointLog) GetRuleCode() string {
	if x != nil {
		return x.RuleCode
	}
	return ""
}

func (x *PointLog) GetRelatedType() string {
	if x != nil {
		return x.RelatedType
	}
	return ""
}

func (x *PointLog) GetRelatedId() uint32 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *PointLog) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *PointLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 积分规则（管理员可配，分值不写死在代码里）
type PointRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                // 唯一标识，如 checkin_daily
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                // 展示名
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`     // 触发事件：checkin / publish_article / weekly_rank ...
	Condition     string                 `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`                      // JSON 条件，如 {"streak":7}、{"rank_lte":10}
	Points        int64                  `protobuf:"varint,6,opt,name=points,proto3" json:"points,omitempty"`                           // 奖励积分
	LimitType     string                 `protobuf:"bytes,7,opt,name=limit_type,json=limitType,proto3" json:"limit_type,omitempty"`     // none / daily / weekly / once（防刷）
	LimitCount    int32                  `protobuf:"varint,8,opt,name=limit_count,json=limitCount,proto3" json:"limit_count,omitempty"` // 限次窗口内最多发放次数
	Status        uint32                 `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`                           // 1=启用 0=停用
	Sort          int32                  `protobuf:"varint,10,opt,name=sort,proto3" json:"sort,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointRule) Reset() {
	*x = PointRule{}
	mi := &file_point_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointRule) ProtoMessage() {}

func (x *PointRule) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointRule.ProtoReflect.Descriptor instead.
func (*PointRule) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{2}
}

func (x *PointRule) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PointRule) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PointRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PointRule) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PointRule) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *PointRule) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *PointRule) GetLimitType() string {
	if x != nil {
		return x.LimitType
	}
	return ""
}

func (x *PointRule) GetLimitCount() int32 {
	if x != nil {
		return x.LimitCount
	}
	return 0
}

func (x *PointRule) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PointRule) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PointRule) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PointRule) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 签到结果
type CheckInResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streak        uint32                 `protobuf:"varint,1,opt,name=streak,proto3" json:"streak,omitempty"` // 本次签到后的连续天数
	Points        int64                  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"` // 本次获得积分
	Rules         []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`    // 命中的规则 code 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInResult) Reset() {
	*x = CheckInResult{}
	mi := &file_point_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResult) ProtoMessage() {}

func (x *CheckInResult) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResult.ProtoReflect.Descriptor instead.
func (*CheckInResult) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{3}
}

func (x *CheckInResult) GetStreak() uint32 {
	if x != nil {
		return x.Streak
	}
	return 0
}

func (x *CheckInResult) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *CheckInResult) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_point_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{4}
}

type CheckInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *CheckInResult         `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInResponse) Reset() {
	*x = CheckInResponse{}
	mi := &file_point_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse) ProtoMessage() {}

func (x *CheckInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse.ProtoReflect.Descriptor instead.
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{5}
}

func (x *CheckInResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CheckInResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckInResponse) GetResult() *CheckInResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// 签到状态（只读，供前端渲染「今日是否已签到」）
type CheckinStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckedInToday  bool                   `protobuf:"varint,1,opt,name=checked_in_today,json=checkedInToday,proto3" json:"checked_in_today,omitempty"`   // 今日是否已签到
	Streak          uint32                 `protobuf:"varint,2,opt,name=streak,proto3" json:"streak,omitempty"`                                           // 当前连续签到天数（今天未签到但昨天签到了仍保留；断了则为 0）
	LastCheckinDate string                 `protobuf:"bytes,3,opt,name=last_checkin_date,json=lastCheckinDate,proto3" json:"last_checkin_date,omitempty"` // 最近一次签到日期 YYYY-MM-DD（无记录则空）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckinStatus) Reset() {
	*x = CheckinStatus{}
	mi := &file_point_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckinStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinStatus) ProtoMessage() {}

func (x *CheckinStatus) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinStatus.ProtoReflect.Descriptor instead.
func (*CheckinStatus) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{6}
}

func (x *CheckinStatus) GetCheckedInToday() bool {
	if x != nil {
		return x.CheckedInToday
	}
	return false
}

func (x *CheckinStatus) GetStreak() uint32 {
	if x != nil {
		return x.Streak
	}
	return 0
}

func (x *CheckinStatus) GetLastCheckinDate() string {
	if x != nil {
		return x.LastCheckinDate
	}
	return ""
}

type GetCheckinStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckinStatusRequest) Reset() {
	*x = GetCheckinStatusRequest{}
	mi := &file_point_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckinStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckinStatusRequest) ProtoMessage() {}

func (x *GetCheckinStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckinStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCheckinStatusRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{7}
}

type GetCheckinStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        *CheckinStatus         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckinStatusResponse) Reset() {
	*x = GetCheckinStatusResponse{}
	mi := &file_point_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckinStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckinStatusResponse) ProtoMessage() {}

func (x *GetCheckinStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckinStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCheckinStatusResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{8}
}

func (x *GetCheckinStatusResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCheckinStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCheckinStatusResponse) GetStatus() *CheckinStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetMyPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyPointsRequest) Reset() {
	*x = GetMyPointsRequest{}
	mi := &file_point_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyPointsRequest) ProtoMessage() {}

func (x *GetMyPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyPointsRequest.ProtoReflect.Descriptor instead.
func (*GetMyPointsRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{9}
}

type GetMyPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Point         *UserPoint             `protobuf:"bytes,3,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyPointsResponse) Reset() {
	*x = GetMyPointsResponse{}
	mi := &file_point_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyPointsResponse) ProtoMessage() {}

func (x *GetMyPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyPointsResponse.ProtoReflect.Descriptor instead.
func (*GetMyPointsResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{10}
}

func (x *GetMyPointsResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetMyPointsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMyPointsResponse) GetPoint() *UserPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

type GetPointLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointLogsRequest) Reset() {
	*x = GetPointLogsRequest{}
	mi := &file_point_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointLogsRequest) ProtoMessage() {}

func (x *GetPointLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointLogsRequest.ProtoReflect.Descriptor instead.
func (*GetPointLogsRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{11}
}

func (x *GetPointLogsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPointLogsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetPointLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Logs          []*PointLog            `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointLogsResponse) Reset() {
	*x = GetPointLogsResponse{}
	mi := &file_point_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointLogsResponse) ProtoMessage() {}

func (x *GetPointLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointLogsResponse.ProtoReflect.Descriptor instead.
func (*GetPointLogsResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{12}
}

func (x *GetPointLogsResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPointLogsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPointLogsResponse) GetLogs() []*PointLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetPointLogsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 事件加分（内部 / 业务服务调用）
type EarnPointsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventType      string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`       // checkin / publish_article / weekly_rank / article_purchased ...
	UserId         uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 目标用户；为 0 时取当前登录用户
	Context        string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`                            // JSON 上下文，供 condition 匹配（如 {"streak":7,"rank":3}）
	RelatedType    string                 `protobuf:"bytes,4,opt,name=related_type,json=relatedType,proto3" json:"related_type,omitempty"` // article / background ...
	RelatedId      uint32                 `protobuf:"varint,5,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // 可选：幂等键；为空时由服务端按 user+event+related 派生
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EarnPointsRequest) Reset() {
	*x = EarnPointsRequest{}
	mi := &file_point_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarnPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarnPointsRequest) ProtoMessage() {}

func (x *EarnPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarnPointsRequest.ProtoReflect.Descriptor instead.
func (*EarnPointsRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{13}
}

func (x *EarnPointsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EarnPointsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EarnPointsRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *EarnPointsRequest) GetRelatedType() string {
	if x != nil {
		return x.RelatedType
	}
	return ""
}

func (x *EarnPointsRequest) GetRelatedId() uint32 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *EarnPointsRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type EarnPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Points        int64                  `protobuf:"varint,3,opt,name=points,proto3" json:"points,omitempty"` // 实际发放积分
	Rules         []string               `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`    // 命中的规则 code 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EarnPointsResponse) Reset() {
	*x = EarnPointsResponse{}
	mi := &file_point_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarnPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarnPointsResponse) ProtoMessage() {}

func (x *EarnPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarnPointsResponse.ProtoReflect.Descriptor instead.
func (*EarnPointsResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{14}
}

func (x *EarnPointsResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EarnPointsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EarnPointsResponse) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *EarnPointsResponse) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

// 消费积分（购买付费文章 / 背景等）
type SpendPointsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 为 0 时取当前登录用户
	Amount         int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                    // 消费积分（正数）
	ItemType       string                 `protobuf:"bytes,3,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // article / background
	ItemId         uint32                 `protobuf:"varint,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Remark         string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // 可选：幂等键；为空时由服务端按 user+item 派生
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpendPointsRequest) Reset() {
	*x = SpendPointsRequest{}
	mi := &file_point_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendPointsRequest) ProtoMessage() {}

func (x *SpendPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendPointsRequest.ProtoReflect.Descriptor instead.
func (*SpendPointsRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{15}
}

func (x *SpendPointsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SpendPointsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SpendPointsRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *SpendPointsRequest) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *SpendPointsRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *SpendPointsRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SpendPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"` // 消费后余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpendPointsResponse) Reset() {
	*x = SpendPointsResponse{}
	mi := &file_point_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendPointsResponse) ProtoMessage() {}

func (x *SpendPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendPointsResponse.ProtoReflect.Descriptor instead.
func (*SpendPointsResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{16}
}

func (x *SpendPointsResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SpendPointsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SpendPointsResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type HasPurchasedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 为 0 时取当前登录用户
	ItemType      string                 `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // article / background
	ItemId        uint32                 `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPurchasedRequest) Reset() {
	*x = HasPurchasedRequest{}
	mi := &file_point_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPurchasedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPurchasedRequest) ProtoMessage() {}

func (x *HasPurchasedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPurchasedRequest.ProtoReflect.Descriptor instead.
func (*HasPurchasedRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{17}
}

func (x *HasPurchasedRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HasPurchasedRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *HasPurchasedRequest) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type HasPurchasedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Purchased     bool                   `protobuf:"varint,3,opt,name=purchased,proto3" json:"purchased,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPurchasedResponse) Reset() {
	*x = HasPurchasedResponse{}
	mi := &file_point_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPurchasedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPurchasedResponse) ProtoMessage() {}

func (x *HasPurchasedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPurchasedResponse.ProtoReflect.Descriptor instead.
func (*HasPurchasedResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{18}
}

func (x *HasPurchasedResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HasPurchasedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HasPurchasedResponse) GetPurchased() bool {
	if x != nil {
		return x.Purchased
	}
	return false
}

type AdminListRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListRulesRequest) Reset() {
	*x = AdminListRulesRequest{}
	mi := &file_point_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListRulesRequest) ProtoMessage() {}

func (x *AdminListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListRulesRequest.ProtoReflect.Descriptor instead.
func (*AdminListRulesRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{19}
}

type AdminListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Rules         []*PointRule           `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListRulesResponse) Reset() {
	*x = AdminListRulesResponse{}
	mi := &file_point_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListRulesResponse) ProtoMessage() {}

func (x *AdminListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListRulesResponse.ProtoReflect.Descriptor instead.
func (*AdminListRulesResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{20}
}

func (x *AdminListRulesResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminListRulesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminListRulesResponse) GetRules() []*PointRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AdminCreateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Condition     string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	Points        int64                  `protobuf:"varint,5,opt,name=points,proto3" json:"points,omitempty"`
	LimitType     string                 `protobuf:"bytes,6,opt,name=limit_type,json=limitType,proto3" json:"limit_type,omitempty"`
	LimitCount    int32                  `protobuf:"varint,7,opt,name=limit_count,json=limitCount,proto3" json:"limit_count,omitempty"`
	Sort          int32                  `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCreateRuleRequest) Reset() {
	*x = AdminCreateRuleRequest{}
	mi := &file_point_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreateRuleRequest) ProtoMessage() {}

func (x *AdminCreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreateRuleRequest.ProtoReflect.Descriptor instead.
func (*AdminCreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{21}
}

func (x *AdminCreateRuleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AdminCreateRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminCreateRuleRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AdminCreateRuleRequest) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *AdminCreateRuleRequest) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *AdminCreateRuleRequest) GetLimitType() string {
	if x != nil {
		return x.LimitType
	}
	return ""
}

func (x *AdminCreateRuleRequest) GetLimitCount() int32 {
	if x != nil {
		return x.LimitCount
	}
	return 0
}

func (x *AdminCreateRuleRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type AdminCreateRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Rule          *PointRule             `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCreateRuleResponse) Reset() {
	*x = AdminCreateRuleResponse{}
	mi := &file_point_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCreateRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCreateRuleResponse) ProtoMessage() {}

func (x *AdminCreateRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCreateRuleResponse.ProtoReflect.Descriptor instead.
func (*AdminCreateRuleResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{22}
}

func (x *AdminCreateRuleResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminCreateRuleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminCreateRuleResponse) GetRule() *PointRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type AdminUpdateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        uint32                 `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Condition     string                 `protobuf:"bytes,3,opt,name=condition,proto3" json:"condition,omitempty"`
	Points        int64                  `protobuf:"varint,4,opt,name=points,proto3" json:"points,omitempty"`
	LimitType     string                 `protobuf:"bytes,5,opt,name=limit_type,json=limitType,proto3" json:"limit_type,omitempty"`
	LimitCount    int32                  `protobuf:"varint,6,opt,name=limit_count,json=limitCount,proto3" json:"limit_count,omitempty"`
	Status        uint32                 `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Sort          int32                  `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateRuleRequest) Reset() {
	*x = AdminUpdateRuleRequest{}
	mi := &file_point_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateRuleRequest) ProtoMessage() {}

func (x *AdminUpdateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateRuleRequest.ProtoReflect.Descriptor instead.
func (*AdminUpdateRuleRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{23}
}

func (x *AdminUpdateRuleRequest) GetRuleId() uint32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *AdminUpdateRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminUpdateRuleRequest) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *AdminUpdateRuleRequest) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *AdminUpdateRuleRequest) GetLimitType() string {
	if x != nil {
		return x.LimitType
	}
	return ""
}

func (x *AdminUpdateRuleRequest) GetLimitCount() int32 {
	if x != nil {
		return x.LimitCount
	}
	return 0
}

func (x *AdminUpdateRuleRequest) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminUpdateRuleRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type AdminUpdateRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Rule          *PointRule             `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateRuleResponse) Reset() {
	*x = AdminUpdateRuleResponse{}
	mi := &file_point_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateRuleResponse) ProtoMessage() {}

func (x *AdminUpdateRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateRuleResponse.ProtoReflect.Descriptor instead.
func (*AdminUpdateRuleResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{24}
}

func (x *AdminUpdateRuleResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminUpdateRuleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminUpdateRuleResponse) GetRule() *PointRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type AdminDeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        uint32                 `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteRuleRequest) Reset() {
	*x = AdminDeleteRuleRequest{}
	mi := &file_point_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteRuleRequest) ProtoMessage() {}

func (x *AdminDeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*AdminDeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{25}
}

func (x *AdminDeleteRuleRequest) GetRuleId() uint32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

type AdminDeleteRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteRuleResponse) Reset() {
	*x = AdminDeleteRuleResponse{}
	mi := &file_point_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteRuleResponse) ProtoMessage() {}

func (x *AdminDeleteRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteRuleResponse.ProtoReflect.Descriptor instead.
func (*AdminDeleteRuleResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{26}
}

func (x *AdminDeleteRuleResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminDeleteRuleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 管理员手动调整积分（纠错 / 运营发放）
type AdminAdjustPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // 正=发放，负=扣减
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAdjustPointsRequest) Reset() {
	*x = AdminAdjustPointsRequest{}
	mi := &file_point_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAdjustPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAdjustPointsRequest) ProtoMessage() {}

func (x *AdminAdjustPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAdjustPointsRequest.ProtoReflect.Descriptor instead.
func (*AdminAdjustPointsRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{27}
}

func (x *AdminAdjustPointsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminAdjustPointsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AdminAdjustPointsRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type AdminAdjustPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"` // 调整后余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAdjustPointsResponse) Reset() {
	*x = AdminAdjustPointsResponse{}
	mi := &file_point_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAdjustPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAdjustPointsResponse) ProtoMessage() {}

func (x *AdminAdjustPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAdjustPointsResponse.ProtoReflect.Descriptor instead.
func (*AdminAdjustPointsResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{28}
}

func (x *AdminAdjustPointsResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminAdjustPointsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminAdjustPointsResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_point_proto protoreflect.FileDescriptor

const file_point_proto_rawDesc = "" +
	"\n" +
	"\vpoint.proto\x12\bpoint.v1\"\xa1\x01\n" +
	"\tUserPoint\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x12!\n" +
	"\ftotal_earned\x18\x03 \x01(\x03R\vtotalEarned\x12\x1f\n" +
	"\vtotal_spent\x18\x04 \x01(\x03R\n" +
	"totalSpent\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"\x9a\x02\n" +
	"\bPointLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12#\n" +
	"\rbalance_after\x18\x04 \x01(\x03R\fbalanceAfter\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1b\n" +
	"\trule_code\x18\x06 \x01(\tR\bruleCode\x12!\n" +
	"\frelated_type\x18\a \x01(\tR\vrelatedType\x12\x1d\n" +
	"\n" +
	"related_id\x18\b \x01(\rR\trelatedId\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"\xc2\x02\n" +
	"\tPointRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x1c\n" +
	"\tcondition\x18\x05 \x01(\tR\tcondition\x12\x16\n" +
	"\x06points\x18\x06 \x01(\x03R\x06points\x12\x1d\n" +
	"\n" +
	"limit_type\x18\a \x01(\tR\tlimitType\x12\x1f\n" +
	"\vlimit_count\x18\b \x01(\x05R\n" +
	"limitCount\x12\x16\n" +
	"\x06status\x18\t \x01(\rR\x06status\x12\x12\n" +
	"\x04sort\x18\n" +
	" \x01(\x05R\x04sort\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"U\n" +
	"\rCheckInResult\x12\x16\n" +
	"\x06streak\x18\x01 \x01(\rR\x06streak\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x03R\x06points\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rules\"\x10\n" +
	"\x0eCheckInRequest\"p\n" +
	"\x0fCheckInResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x06result\x18\x03 \x01(\v2\x17.point.v1.CheckInResultR\x06result\"}\n" +
	"\rCheckinStatus\x12(\n" +
	"\x10checked_in_today\x18\x01 \x01(\bR\x0echeckedInToday\x12\x16\n" +
	"\x06streak\x18\x02 \x01(\rR\x06streak\x12*\n" +
	"\x11last_checkin_date\x18\x03 \x01(\tR\x0flastCheckinDate\"\x19\n" +
	"\x17GetCheckinStatusRequest\"y\n" +
	"\x18GetCheckinStatusResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x06status\x18\x03 \x01(\v2\x17.point.v1.CheckinStatusR\x06status\"\x14\n" +
	"\x12GetMyPointsRequest\"n\n" +
	"\x13GetMyPointsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x05point\x18\x03 \x01(\v2\x13.point.v1.UserPointR\x05point\"F\n" +
	"\x13GetPointLogsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\"\x82\x01\n" +
	"\x14GetPointLogsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04logs\x18\x03 \x03(\v2\x12.point.v1.PointLogR\x04logs\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"\xd0\x01\n" +
	"\x11EarnPointsRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12!\n" +
	"\frelated_type\x18\x04 \x01(\tR\vrelatedType\x12\x1d\n" +
	"\n" +
	"related_id\x18\x05 \x01(\rR\trelatedId\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"p\n" +
	"\x12EarnPointsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06points\x18\x03 \x01(\x03R\x06points\x12\x14\n" +
	"\x05rules\x18\x04 \x03(\tR\x05rules\"\xbc\x01\n" +
	"\x12SpendPointsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1b\n" +
	"\titem_type\x18\x03 \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\rR\x06itemId\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"]\n" +
	"\x13SpendPointsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\"d\n" +
	"\x13HasPurchasedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\tR\bitemType\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\rR\x06itemId\"b\n" +
	"\x14HasPurchasedResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tpurchased\x18\x03 \x01(\bR\tpurchased\"\x17\n" +
	"\x15AdminListRulesRequest\"q\n" +
	"\x16AdminListRulesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x05rules\x18\x03 \x03(\v2\x13.point.v1.PointRuleR\x05rules\"\xe9\x01\n" +
	"\x16AdminCreateRuleRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\x12\x16\n" +
	"\x06points\x18\x05 \x01(\x03R\x06points\x12\x1d\n" +
	"\n" +
	"limit_type\x18\x06 \x01(\tR\tlimitType\x12\x1f\n" +
	"\vlimit_count\x18\a \x01(\x05R\n" +
	"limitCount\x12\x12\n" +
	"\x04sort\x18\b \x01(\x05R\x04sort\"p\n" +
	"\x17AdminCreateRuleResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04rule\x18\x03 \x01(\v2\x13.point.v1.PointRuleR\x04rule\"\xe7\x01\n" +
	"\x16AdminUpdateRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\rR\x06ruleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tcondition\x18\x03 \x01(\tR\tcondition\x12\x16\n" +
	"\x06points\x18\x04 \x01(\x03R\x06points\x12\x1d\n" +
	"\n" +
	"limit_type\x18\x05 \x01(\tR\tlimitType\x12\x1f\n" +
	"\vlimit_count\x18\x06 \x01(\x05R\n" +
	"limitCount\x12\x16\n" +
	"\x06status\x18\a \x01(\rR\x06status\x12\x12\n" +
	"\x04sort\x18\b \x01(\x05R\x04sort\"p\n" +
	"\x17AdminUpdateRuleResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04rule\x18\x03 \x01(\v2\x13.point.v1.PointRuleR\x04rule\"1\n" +
	"\x16AdminDeleteRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\rR\x06ruleId\"G\n" +
	"\x17AdminDeleteRuleResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"c\n" +
	"\x18AdminAdjustPointsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"c\n" +
	"\x19AdminAdjustPointsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance*\xdf\x01\n" +
	"\x0ePointErrorCode\x12\x11\n" +
	"\rPOINT_SUCCESS\x10\x00\x12\x19\n" +
	"\x14POINT_INTERNAL_ERROR\x10\x95N\x12\x15\n" +
	"\x0fPOINT_NOT_FOUND\x10\xe1\xd4\x03\x12\x17\n" +
	"\x11POINT_BAD_REQUEST\x10\xe2\xd4\x03\x12\x18\n" +
	"\x12POINT_INSUFFICIENT\x10\xe3\xd4\x03\x12\x1e\n" +
	"\x18POINT_ALREADY_CHECKED_IN\x10\xe4\xd4\x03\x12\x1a\n" +
	"\x14POINT_RULE_NOT_FOUND\x10\xe5\xd4\x03\x12\x19\n" +
	"\x13POINT_LIMIT_REACHED\x10\xe6\xd4\x032\xff\x05\n" +
	"\fPointService\x12>\n" +
	"\aCheckIn\x12\x18.point.v1.CheckInRequest\x1a\x19.point.v1.CheckInResponse\x12J\n" +
	"\vGetMyPoints\x12\x1c.point.v1.GetMyPointsRequest\x1a\x1d.point.v1.GetMyPointsResponse\x12M\n" +
	"\fGetPointLogs\x12\x1d.point.v1.GetPointLogsRequest\x1a\x1e.point.v1.GetPointLogsResponse\x12Y\n" +
	"\x10GetCheckinStatus\x12!.point.v1.GetCheckinStatusRequest\x1a\".point.v1.GetCheckinStatusResponse\x12S\n" +
	"\x0eAdminListRules\x12\x1f.point.v1.AdminListRulesRequest\x1a .point.v1.AdminListRulesResponse\x12V\n" +
	"\x0fAdminCreateRule\x12 .point.v1.AdminCreateRuleRequest\x1a!.point.v1.AdminCreateRuleResponse\x12V\n" +
	"\x0fAdminUpdateRule\x12 .point.v1.AdminUpdateRuleRequest\x1a!.point.v1.AdminUpdateRuleResponse\x12V\n" +
	"\x0fAdminDeleteRule\x12 .point.v1.AdminDeleteRuleRequest\x1a!.point.v1.AdminDeleteRuleResponse\x12\\\n" +
	"\x11AdminAdjustPoints\x12\".point.v1.AdminAdjustPointsRequest\x1a#.point.v1.AdminAdjustPointsResponseB/Z-github.com/mysunshines/blog-point/proto/pb/v1b\x06proto3"

var (
	file_point_proto_rawDescOnce sync.Once
	file_point_proto_rawDescData []byte
)

func file_point_proto_rawDescGZIP() []byte {
	file_point_proto_rawDescOnce.Do(func() {
		file_point_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_point_proto_rawDesc), len(file_point_proto_rawDesc)))
	})
	return file_point_proto_rawDescData
}

var file_point_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_point_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_point_proto_goTypes = []any{
	(PointErrorCode)(0),               // 0: point.v1.PointErrorCode
	(*UserPoint)(nil),                 // 1: point.v1.UserPoint
	(*PointLog)(nil),                  // 2: point.v1.PointLog
	(*PointRule)(nil),                 // 3: point.v1.PointRule
	(*CheckInResult)(nil),             // 4: point.v1.CheckInResult
	(*CheckInRequest)(nil),            // 5: point.v1.CheckInRequest
	(*CheckInResponse)(nil),           // 6: point.v1.CheckInResponse
	(*CheckinStatus)(nil),             // 7: point.v1.CheckinStatus
	(*GetCheckinStatusRequest)(nil),   // 8: point.v1.GetCheckinStatusRequest
	(*GetCheckinStatusResponse)(nil),  // 9: point.v1.GetCheckinStatusResponse
	(*GetMyPointsRequest)(nil),        // 10: point.v1.GetMyPointsRequest
	(*GetMyPointsResponse)(nil),       // 11: point.v1.GetMyPointsResponse
	(*GetPointLogsRequest)(nil),       // 12: point.v1.GetPointLogsRequest
	(*GetPointLogsResponse)(nil),      // 13: point.v1.GetPointLogsResponse
	(*EarnPointsRequest)(nil),         // 14: point.v1.EarnPointsRequest
	(*EarnPointsResponse)(nil),        // 15: point.v1.EarnPointsResponse
	(*SpendPointsRequest)(nil),        // 16: point.v1.SpendPointsRequest
	(*SpendPointsResponse)(nil),       // 17: point.v1.SpendPointsResponse
	(*HasPurchasedRequest)(nil),       // 18: point.v1.HasPurchasedRequest
	(*HasPurchasedResponse)(nil),      // 19: point.v1.HasPurchasedResponse
	(*AdminListRulesRequest)(nil),     // 20: point.v1.AdminListRulesRequest
	(*AdminListRulesResponse)(nil),    // 21: point.v1.AdminListRulesResponse
	(*AdminCreateRuleRequest)(nil),    // 22: point.v1.AdminCreateRuleRequest
	(*AdminCreateRuleResponse)(nil),   // 23: point.v1.AdminCreateRuleResponse
	(*AdminUpdateRuleRequest)(nil),    // 24: point.v1.AdminUpdateRuleRequest
	(*AdminUpdateRuleResponse)(nil),   // 25: point.v1.AdminUpdateRuleResponse
	(*AdminDeleteRuleRequest)(nil),    // 26: point.v1.AdminDeleteRuleRequest
	(*AdminDeleteRuleResponse)(nil),   // 27: point.v1.AdminDeleteRuleResponse
	(*AdminAdjustPointsRequest)(nil),  // 28: point.v1.AdminAdjustPointsRequest
	(*AdminAdjustPointsResponse)(nil), // 29: point.v1.AdminAdjustPointsResponse
}
var file_point_proto_depIdxs = []int32{
	4,  // 0: point.v1.CheckInResponse.result:type_name -> point.v1.CheckInResult
	7,  // 1: point.v1.GetCheckinStatusResponse.status:type_name -> point.v1.CheckinStatus
	1,  // 2: point.v1.GetMyPointsResponse.point:type_name -> point.v1.UserPoint
	2,  // 3: point.v1.GetPointLogsResponse.logs:type_name -> point.v1.PointLog
	3,  // 4: point.v1.AdminListRulesResponse.rules:type_name -> point.v1.PointRule
	3,  // 5: point.v1.AdminCreateRuleResponse.rule:type_name -> point.v1.PointRule
	3,  // 6: point.v1.AdminUpdateRuleResponse.rule:type_name -> point.v1.PointRule
	5,  // 7: point.v1.PointService.CheckIn:input_type -> point.v1.CheckInRequest
	10, // 8: point.v1.PointService.GetMyPoints:input_type -> point.v1.GetMyPointsRequest
	12, // 9: point.v1.PointService.GetPointLogs:input_type -> point.v1.GetPointLogsRequest
	8,  // 10: point.v1.PointService.GetCheckinStatus:input_type -> point.v1.GetCheckinStatusRequest
	20, // 11: point.v1.PointService.AdminListRules:input_type -> point.v1.AdminListRulesRequest
	22, // 12: point.v1.PointService.AdminCreateRule:input_type -> point.v1.AdminCreateRuleRequest
	24, // 13: point.v1.PointService.AdminUpdateRule:input_type -> point.v1.AdminUpdateRuleRequest
	26, // 14: point.v1.PointService.AdminDeleteRule:input_type -> point.v1.AdminDeleteRuleRequest
	28, // 15: point.v1.PointService.AdminAdjustPoints:input_type -> point.v1.AdminAdjustPointsRequest
	6,  // 16: point.v1.PointService.CheckIn:output_type -> point.v1.CheckInResponse
	11, // 17: point.v1.PointService.GetMyPoints:output_type -> point.v1.GetMyPointsResponse
	13, // 18: point.v1.PointService.GetPointLogs:output_type -> point.v1.GetPointLogsResponse
	9,  // 19: point.v1.PointService.GetCheckinStatus:output_type -> point.v1.GetCheckinStatusResponse
	21, // 20: point.v1.PointService.AdminListRules:output_type -> point.v1.AdminListRulesResponse
	23, // 21: point.v1.PointService.AdminCreateRule:output_type -> point.v1.AdminCreateRuleResponse
	25, // 22: point.v1.PointService.AdminUpdateRule:output_type -> point.v1.AdminUpdateRuleResponse
	27, // 23: point.v1.PointService.AdminDeleteRule:output_type -> point.v1.AdminDeleteRuleResponse
	29, // 24: point.v1.PointService.AdminAdjustPoints:output_type -> point.v1.AdminAdjustPointsResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_point_proto_init() }
func file_point_proto_init() {
	if File_point_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_point_proto_rawDesc), len(file_point_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_point_proto_goTypes,
		DependencyIndexes: file_point_proto_depIdxs,
		EnumInfos:         file_point_proto_enumTypes,
		MessageInfos:      file_point_proto_msgTypes,
	}.Build()
	File_point_proto = out.File
	file_point_proto_goTypes = nil
	file_point_proto_depIdxs = nil
}
