// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: point.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PointService_CheckIn_FullMethodName           = "/point.v1.PointService/CheckIn"
	PointService_GetMyPoints_FullMethodName       = "/point.v1.PointService/GetMyPoints"
	PointService_GetPointLogs_FullMethodName      = "/point.v1.PointService/GetPointLogs"
	PointService_GetCheckinStatus_FullMethodName  = "/point.v1.PointService/GetCheckinStatus"
	PointService_AdminListRules_FullMethodName    = "/point.v1.PointService/AdminListRules"
	PointService_AdminCreateRule_FullMethodName   = "/point.v1.PointService/AdminCreateRule"
	PointService_AdminUpdateRule_FullMethodName   = "/point.v1.PointService/AdminUpdateRule"
	PointService_AdminDeleteRule_FullMethodName   = "/point.v1.PointService/AdminDeleteRule"
	PointService_AdminAdjustPoints_FullMethodName = "/point.v1.PointService/AdminAdjustPoints"
)

// PointServiceClient is the client API for PointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PointServiceClient interface {
	// --------------------------- 用户侧（需登录） ---------------------------
	CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error)
	GetMyPoints(ctx context.Context, in *GetMyPointsRequest, opts ...grpc.CallOption) (*GetMyPointsResponse, error)
	GetPointLogs(ctx context.Context, in *GetPointLogsRequest, opts ...grpc.CallOption) (*GetPointLogsResponse, error)
	GetCheckinStatus(ctx context.Context, in *GetCheckinStatusRequest, opts ...grpc.CallOption) (*GetCheckinStatusResponse, error)
	// --------------------------- 后台管理（管理员，RequireGRPCAdmin） ---------------------------
	AdminListRules(ctx context.Context, in *AdminListRulesRequest, opts ...grpc.CallOption) (*AdminListRulesResponse, error)
	AdminCreateRule(ctx context.Context, in *AdminCreateRuleRequest, opts ...grpc.CallOption) (*AdminCreateRuleResponse, error)
	AdminUpdateRule(ctx context.Context, in *AdminUpdateRuleRequest, opts ...grpc.CallOption) (*AdminUpdateRuleResponse, error)
	AdminDeleteRule(ctx context.Context, in *AdminDeleteRuleRequest, opts ...grpc.CallOption) (*AdminDeleteRuleResponse, error)
	AdminAdjustPoints(ctx context.Context, in *AdminAdjustPointsRequest, opts ...grpc.CallOption) (*AdminAdjustPointsResponse, error)
}

type pointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPointServiceClient(cc grpc.ClientConnInterface) PointServiceClient {
	return &pointServiceClient{cc}
}

func (c *pointServiceClient) CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckInResponse)
	err := c.cc.Invoke(ctx, PointService_CheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) GetMyPoints(ctx context.Context, in *GetMyPointsRequest, opts ...grpc.CallOption) (*GetMyPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyPointsResponse)
	err := c.cc.Invoke(ctx, PointService_GetMyPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) GetPointLogs(ctx context.Context, in *GetPointLogsRequest, opts ...grpc.CallOption) (*GetPointLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPointLogsResponse)
	err := c.cc.Invoke(ctx, PointService_GetPointLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) GetCheckinStatus(ctx context.Context, in *GetCheckinStatusRequest, opts ...grpc.CallOption) (*GetCheckinStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckinStatusResponse)
	err := c.cc.Invoke(ctx, PointService_GetCheckinStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) AdminListRules(ctx context.Context, in *AdminListRulesRequest, opts ...grpc.CallOption) (*AdminListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListRulesResponse)
	err := c.cc.Invoke(ctx, PointService_AdminListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) AdminCreateRule(ctx context.Context, in *AdminCreateRuleRequest, opts ...grpc.CallOption) (*AdminCreateRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCreateRuleResponse)
	err := c.cc.Invoke(ctx, PointService_AdminCreateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) AdminUpdateRule(ctx context.Context, in *AdminUpdateRuleRequest, opts ...grpc.CallOption) (*AdminUpdateRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpdateRuleResponse)
	err := c.cc.Invoke(ctx, PointService_AdminUpdateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) AdminDeleteRule(ctx context.Context, in *AdminDeleteRuleRequest, opts ...grpc.CallOption) (*AdminDeleteRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeleteRuleResponse)
	err := c.cc.Invoke(ctx, PointService_AdminDeleteRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) AdminAdjustPoints(ctx context.Context, in *AdminAdjustPointsRequest, opts ...grpc.CallOption) (*AdminAdjustPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAdjustPointsResponse)
	err := c.cc.Invoke(ctx, PointService_AdminAdjustPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PointServiceServer is the server API for PointService service.
// All implementations must embed UnimplementedPointServiceServer
// for forward compatibility.
type PointServiceServer interface {
	// --------------------------- 用户侧（需登录） ---------------------------
	CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error)
	GetMyPoints(context.Context, *GetMyPointsRequest) (*GetMyPointsResponse, error)
	GetPointLogs(context.Context, *GetPointLogsRequest) (*GetPointLogsResponse, error)
	GetCheckinStatus(context.Context, *GetCheckinStatusRequest) (*GetCheckinStatusResponse, error)
	// --------------------------- 后台管理（管理员，RequireGRPCAdmin） ---------------------------
	AdminListRules(context.Context, *AdminListRulesRequest) (*AdminListRulesResponse, error)
	AdminCreateRule(context.Context, *AdminCreateRuleRequest) (*AdminCreateRuleResponse, error)
	AdminUpdateRule(context.Context, *AdminUpdateRuleRequest) (*AdminUpdateRuleResponse, error)
	AdminDeleteRule(context.Context, *AdminDeleteRuleRequest) (*AdminDeleteRuleResponse, error)
	AdminAdjustPoints(context.Context, *AdminAdjustPointsRequest) (*AdminAdjustPointsResponse, error)
	mustEmbedUnimplementedPointServiceServer()
}

// UnimplementedPointServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPointServiceServer struct{}

func (UnimplementedPointServiceServer) CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedPointServiceServer) GetMyPoints(context.Context, *GetMyPointsRequest) (*GetMyPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyPoints not implemented")
}
func (UnimplementedPointServiceServer) GetPointLogs(context.Context, *GetPointLogsRequest) (*GetPointLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPointLogs not implemented")
}
func (UnimplementedPointServiceServer) GetCheckinStatus(context.Context, *GetCheckinStatusRequest) (*GetCheckinStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCheckinStatus not implemented")
}
func (UnimplementedPointServiceServer) AdminListRules(context.Context, *AdminListRulesRequest) (*AdminListRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListRules not implemented")
}
func (UnimplementedPointServiceServer) AdminCreateRule(context.Context, *AdminCreateRuleRequest) (*AdminCreateRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminCreateRule not implemented")
}
func (UnimplementedPointServiceServer) AdminUpdateRule(context.Context, *AdminUpdateRuleRequest) (*AdminUpdateRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUpdateRule not implemented")
}
func (UnimplementedPointServiceServer) AdminDeleteRule(context.Context, *AdminDeleteRuleRequest) (*AdminDeleteRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteRule not implemented")
}
func (UnimplementedPointServiceServer) AdminAdjustPoints(context.Context, *AdminAdjustPointsRequest) (*AdminAdjustPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminAdjustPoints not implemented")
}
func (UnimplementedPointServiceServer) mustEmbedUnimplementedPointServiceServer() {}
func (UnimplementedPointServiceServer) testEmbeddedByValue()                      {}

// UnsafePointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PointServiceServer will
// result in compilation errors.
type UnsafePointServiceServer interface {
	mustEmbedUnimplementedPointServiceServer()
}

func RegisterPointServiceServer(s grpc.ServiceRegistrar, srv PointServiceServer) {
	// If the following call panics, it indicates UnimplementedPointServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PointService_ServiceDesc, srv)
}

func _PointService_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_CheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).CheckIn(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_GetMyPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).GetMyPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_GetMyPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).GetMyPoints(ctx, req.(*GetMyPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_GetPointLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPointLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).GetPointLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_GetPointLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).GetPointLogs(ctx, req.(*GetPointLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_GetCheckinStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckinStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).GetCheckinStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_GetCheckinStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).GetCheckinStatus(ctx, req.(*GetCheckinStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_AdminListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).AdminListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_AdminListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).AdminListRules(ctx, req.(*AdminListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_AdminCreateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).AdminCreateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_AdminCreateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).AdminCreateRule(ctx, req.(*AdminCreateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_AdminUpdateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).AdminUpdateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_AdminUpdateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).AdminUpdateRule(ctx, req.(*AdminUpdateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_AdminDeleteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).AdminDeleteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_AdminDeleteRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).AdminDeleteRule(ctx, req.(*AdminDeleteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_AdminAdjustPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminAdjustPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).AdminAdjustPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_AdminAdjustPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).AdminAdjustPoints(ctx, req.(*AdminAdjustPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PointService_ServiceDesc is the grpc.ServiceDesc for PointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "point.v1.PointService",
	HandlerType: (*PointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIn",
			Handler:    _PointService_CheckIn_Handler,
		},
		{
			MethodName: "GetMyPoints",
			Handler:    _PointService_GetMyPoints_Handler,
		},
		{
			MethodName: "GetPointLogs",
			Handler:    _PointService_GetPointLogs_Handler,
		},
		{
			MethodName: "GetCheckinStatus",
			Handler:    _PointService_GetCheckinStatus_Handler,
		},
		{
			MethodName: "AdminListRules",
			Handler:    _PointService_AdminListRules_Handler,
		},
		{
			MethodName: "AdminCreateRule",
			Handler:    _PointService_AdminCreateRule_Handler,
		},
		{
			MethodName: "AdminUpdateRule",
			Handler:    _PointService_AdminUpdateRule_Handler,
		},
		{
			MethodName: "AdminDeleteRule",
			Handler:    _PointService_AdminDeleteRule_Handler,
		},
		{
			MethodName: "AdminAdjustPoints",
			Handler:    _PointService_AdminAdjustPoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "point.proto",
}
