// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: point_ingest.proto

// ============================================================================
// Point 内部摄入契约（v0）：与对外接口（point.v1.PointService）分离。
// ----------------------------------------------------------------------------
// 约定：所有「服务间内部调用」的 gRPC 接口统一置于 v0 包（point.v0.*），
// 与对外 C 端接口（v1）在命名与部署上彻底隔离：
//   - 公网网关（Gateway）按 DeriveGRPCService 仅代理 *.v1.* 服务，v0 天然不进公网入口；
//   - v0 仅由内网服务经 Consul 直连 gRPC 调用，完全信任内网、不做应用层鉴权，
//     安全性依赖 gRPC 端口仅对内网开放（不暴露公网）。
// ============================================================================

package v0

import (
	reflect "reflect"
	unsafe "unsafe"

	v1 "github.com/mysunshines/blog-point/proto/pb/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_point_ingest_proto protoreflect.FileDescriptor

const file_point_ingest_proto_rawDesc = "" +
	"\n" +
	"\x12point_ingest.proto\x12\bpoint.v0\x1a\vpoint.proto2\xf8\x01\n" +
	"\x12PointIngestService\x12G\n" +
	"\n" +
	"EarnPoints\x12\x1b.point.v1.EarnPointsRequest\x1a\x1c.point.v1.EarnPointsResponse\x12J\n" +
	"\vSpendPoints\x12\x1c.point.v1.SpendPointsRequest\x1a\x1d.point.v1.SpendPointsResponse\x12M\n" +
	"\fHasPurchased\x12\x1d.point.v1.HasPurchasedRequest\x1a\x1e.point.v1.HasPurchasedResponseB/Z-github.com/mysunshines/blog-point/proto/pb/v0b\x06proto3"

var file_point_ingest_proto_goTypes = []any{
	(*v1.EarnPointsRequest)(nil),    // 0: point.v1.EarnPointsRequest
	(*v1.SpendPointsRequest)(nil),   // 1: point.v1.SpendPointsRequest
	(*v1.HasPurchasedRequest)(nil),  // 2: point.v1.HasPurchasedRequest
	(*v1.EarnPointsResponse)(nil),   // 3: point.v1.EarnPointsResponse
	(*v1.SpendPointsResponse)(nil),  // 4: point.v1.SpendPointsResponse
	(*v1.HasPurchasedResponse)(nil), // 5: point.v1.HasPurchasedResponse
}
var file_point_ingest_proto_depIdxs = []int32{
	0, // 0: point.v0.PointIngestService.EarnPoints:input_type -> point.v1.EarnPointsRequest
	1, // 1: point.v0.PointIngestService.SpendPoints:input_type -> point.v1.SpendPointsRequest
	2, // 2: point.v0.PointIngestService.HasPurchased:input_type -> point.v1.HasPurchasedRequest
	3, // 3: point.v0.PointIngestService.EarnPoints:output_type -> point.v1.EarnPointsResponse
	4, // 4: point.v0.PointIngestService.SpendPoints:output_type -> point.v1.SpendPointsResponse
	5, // 5: point.v0.PointIngestService.HasPurchased:output_type -> point.v1.HasPurchasedResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_point_ingest_proto_init() }
func file_point_ingest_proto_init() {
	if File_point_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_point_ingest_proto_rawDesc), len(file_point_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_point_ingest_proto_goTypes,
		DependencyIndexes: file_point_ingest_proto_depIdxs,
	}.Build()
	File_point_ingest_proto = out.File
	file_point_ingest_proto_goTypes = nil
	file_point_ingest_proto_depIdxs = nil
}
