// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: point_ingest.proto

// ============================================================================
// Point 内部摄入契约（v0）：与对外接口（point.v1.PointService）分离。
// ----------------------------------------------------------------------------
// 约定：所有「服务间内部调用」的 gRPC 接口统一置于 v0 包（point.v0.*），
// 与对外 C 端接口（v1）在命名与部署上彻底隔离：
//   - 公网网关（Gateway）按 DeriveGRPCService 仅代理 *.v1.* 服务，v0 天然不进公网入口；
//   - v0 仅由内网服务经 Consul 直连 gRPC 调用，完全信任内网、不做应用层鉴权，
//     安全性依赖 gRPC 端口仅对内网开放（不暴露公网）。
// ============================================================================

package v0

import (
	context "context"

	v1 "github.com/mysunshines/blog-point/proto/pb/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PointIngestService_EarnPoints_FullMethodName   = "/point.v0.PointIngestService/EarnPoints"
	PointIngestService_SpendPoints_FullMethodName  = "/point.v0.PointIngestService/SpendPoints"
	PointIngestService_HasPurchased_FullMethodName = "/point.v0.PointIngestService/HasPurchased"
)

// PointIngestServiceClient is the client API for PointIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PointIngestService 内部摄入接口（point.v0，仅内网、仅受信服务）：
// 业务方（article/comment/user）上报积分事件、消费积分、查询购买状态。
type PointIngestServiceClient interface {
	// 事件加分：业务服务上报事件，由规则引擎匹配并计分（分值不写死在调用方）。
	EarnPoints(ctx context.Context, in *v1.EarnPointsRequest, opts ...grpc.CallOption) (*v1.EarnPointsResponse, error)
	// 消费积分：购买付费文章 / 背景等，扣减并记账。
	SpendPoints(ctx context.Context, in *v1.SpendPointsRequest, opts ...grpc.CallOption) (*v1.SpendPointsResponse, error)
	// 查询用户是否已购买某物品（付费文章 / 背景）。
	HasPurchased(ctx context.Context, in *v1.HasPurchasedRequest, opts ...grpc.CallOption) (*v1.HasPurchasedResponse, error)
}

type pointIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPointIngestServiceClient(cc grpc.ClientConnInterface) PointIngestServiceClient {
	return &pointIngestServiceClient{cc}
}

func (c *pointIngestServiceClient) EarnPoints(ctx context.Context, in *v1.EarnPointsRequest, opts ...grpc.CallOption) (*v1.EarnPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.EarnPointsResponse)
	err := c.cc.Invoke(ctx, PointIngestService_EarnPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointIngestServiceClient) SpendPoints(ctx context.Context, in *v1.SpendPointsRequest, opts ...grpc.CallOption) (*v1.SpendPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.SpendPointsResponse)
	err := c.cc.Invoke(ctx, PointIngestService_SpendPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointIngestServiceClient) HasPurchased(ctx context.Context, in *v1.HasPurchasedRequest, opts ...grpc.CallOption) (*v1.HasPurchasedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.HasPurchasedResponse)
	err := c.cc.Invoke(ctx, PointIngestService_HasPurchased_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PointIngestServiceServer is the server API for PointIngestService service.
// All implementations must embed UnimplementedPointIngestServiceServer
// for forward compatibility.
//
// PointIngestService 内部摄入接口（point.v0，仅内网、仅受信服务）：
// 业务方（article/comment/user）上报积分事件、消费积分、查询购买状态。
type PointIngestServiceServer interface {
	// 事件加分：业务服务上报事件，由规则引擎匹配并计分（分值不写死在调用方）。
	EarnPoints(context.Context, *v1.EarnPointsRequest) (*v1.EarnPointsResponse, error)
	// 消费积分：购买付费文章 / 背景等，扣减并记账。
	SpendPoints(context.Context, *v1.SpendPointsRequest) (*v1.SpendPointsResponse, error)
	// 查询用户是否已购买某物品（付费文章 / 背景）。
	HasPurchased(context.Context, *v1.HasPurchasedRequest) (*v1.HasPurchasedResponse, error)
	mustEmbedUnimplementedPointIngestServiceServer()
}

// UnimplementedPointIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPointIngestServiceServer struct{}

func (UnimplementedPointIngestServiceServer) EarnPoints(context.Context, *v1.EarnPointsRequest) (*v1.EarnPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EarnPoints not implemented")
}
func (UnimplementedPointIngestServiceServer) SpendPoints(context.Context, *v1.SpendPointsRequest) (*v1.SpendPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SpendPoints not implemented")
}
func (UnimplementedPointIngestServiceServer) HasPurchased(context.Context, *v1.HasPurchasedRequest) (*v1.HasPurchasedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasPurchased not implemented")
}
func (UnimplementedPointIngestServiceServer) mustEmbedUnimplementedPointIngestServiceServer() {}
func (UnimplementedPointIngestServiceServer) testEmbeddedByValue()                            {}

// UnsafePointIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PointIngestServiceServer will
// result in compilation errors.
type UnsafePointIngestServiceServer interface {
	mustEmbedUnimplementedPointIngestServiceServer()
}

func RegisterPointIngestServiceServer(s grpc.ServiceRegistrar, srv PointIngestServiceServer) {
	// If the following call panics, it indicates UnimplementedPointIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PointIngestService_ServiceDesc, srv)
}

func _PointIngestService_EarnPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.EarnPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointIngestServiceServer).EarnPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointIngestService_EarnPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointIngestServiceServer).EarnPoints(ctx, req.(*v1.EarnPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointIngestService_SpendPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.SpendPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointIngestServiceServer).SpendPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointIngestService_SpendPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointIngestServiceServer).SpendPoints(ctx, req.(*v1.SpendPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointIngestService_HasPurchased_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.HasPurchasedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointIngestServiceServer).HasPurchased(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointIngestService_HasPurchased_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointIngestServiceServer).HasPurchased(ctx, req.(*v1.HasPurchasedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PointIngestService_ServiceDesc is the grpc.ServiceDesc for PointIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PointIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "point.v0.PointIngestService",
	HandlerType: (*PointIngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EarnPoints",
			Handler:    _PointIngestService_EarnPoints_Handler,
		},
		{
			MethodName: "SpendPoints",
			Handler:    _PointIngestService_SpendPoints_Handler,
		},
		{
			MethodName: "HasPurchased",
			Handler:    _PointIngestService_HasPurchased_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "point_ingest.proto",
}
